import {StyleSheet} from 'react-native';
import {heightPercentageToDP as hp} from 'react-native-responsive-screen';
import {colors} from '../../../utils/colors';

export const styles = StyleSheet.create({
  button: {
    backgroundColor: colors.primary,
    padding: 10,
    borderRadius: 8,
  },
  buttonText: {
    fontWeight: 'bold',
    color: colors.secondary,
    fontSize: 12,
  },
  container: {
    flex: 1,
    width: '100%',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  overlay2: {
    position: 'absolute',
    bottom: hp(15),
    borderRadius: 20,
    width: '90%',
  },
  timerContainer: {
    position: 'absolute',
    width: '100%',
    zIndex: 1000,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    left: 0,
    bottom: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    gap: 5,
  },
  timerText: {
    color: 'white',
  },
  buttonContainer: {
    position: 'absolute',
    width: '100%',
    zIndex: 1000,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    left: 0,
    bottom: 50,
    gap: 5,
  },
  // New styles for 3D map and directions
  directionsOverlay: {
    position: 'absolute',
    top: 60,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    borderRadius: 10,
    padding: 15,
    zIndex: 1000,
  },
  directionText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  distanceText: {
    color: '#ccc',
    fontSize: 14,
  },
  driverMarker: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    borderRadius: 25,
    width: 50,
    height: 50,
    borderWidth: 3,
    borderColor: '#FF0000',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  truckIcon: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
  },
  pickupMarker: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#595FE5',
    borderRadius: 20,
    width: 40,
    height: 40,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  dropMarker: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#00C851',
    borderRadius: 20,
    width: 40,
    height: 40,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  markerText: {
    fontSize: 20,
  },
  // Additional control styles
  additionalControls: {
    position: 'absolute',
    width: '100%',
    zIndex: 1000,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    left: 0,
    bottom: 100,
    gap: 10,
  },
  controlButton: {
    backgroundColor: colors.primary,
    padding: 8,
    borderRadius: 6,
    minWidth: 60,
    alignItems: 'center',
  },
  controlButtonText: {
    fontWeight: 'bold',
    color: colors.secondary,
    fontSize: 11,
  },
  activeButton: {
    backgroundColor: '#FF6B35',
  },
  activeButtonText: {
    color: 'white',
  },
}); 