import { I18nManager, Platform, StyleSheet } from 'react-native';
import { colors } from '../../utils/colors';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    backgroundColor: colors.backgroundPrimary,
  },
  scrollContainer: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: hp(5),
    paddingBottom: hp(2.5),
    gap: hp(2),
    width: wp('100%'),
    backgroundColor: colors.backgroundPrimary,
  },
  header: {
    width: '100%',
    paddingStart: wp(5),
    paddingVertical: hp(2),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: hp(3),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  languageButton: {
    padding: 8,
    alignSelf:"flex-end",
    marginHorizontal:wp(4),
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 24,
    backgroundColor: colors.backgroundSecondary,
    shadowColor: colors.uberBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  flagImage: {
    width: 36,
    height: 24,
    borderRadius: 4,
  },
  formContainer: {
    width: '90%',
    alignSelf: 'center',
    marginTop: hp(2),
    marginBottom: hp(2),
  },
  inputContainer: {
    width: '100%',
    marginTop: hp(2),
    marginBottom: hp(1),
  },
  input: {
    width: '100%',
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderLight,
    paddingHorizontal: wp(4),
    paddingVertical: hp(1.8),
    fontSize: hp(1.8),
    color: colors.textPrimary,
    marginBottom: hp(2),
    textAlign:I18nManager.isRTL? "right":"left",
    shadowColor: colors.uberBlack,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  inputError: {
    borderColor: colors.error,
  },
  errorText: {
    color: colors.error,
    fontSize: hp(1.5),
    marginTop: -hp(1.5),
    marginBottom: hp(1),
    marginLeft: wp(1),
  },
  passwordInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderLight,
    marginBottom: hp(1),
    shadowColor: colors.uberBlack,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  passwordInput: {
    flex: 1,
    fontSize: hp(1.8),
    color: colors.textPrimary,
    paddingVertical: hp(1.8),
    paddingHorizontal: wp(4),
    textAlign:I18nManager.isRTL? "right":"left",
  },
  eyeIcon: {
    padding: wp(2),
  },
  forgotPassword: {
    alignSelf: 'flex-end',
    color: colors.textSecondary,
    fontSize: hp(1.6),
    marginBottom: hp(3),
  },
  btn: {
    width: '90%',
    alignSelf:"center",
    paddingVertical: hp(2),
    backgroundColor: colors.uberBlack,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: hp(1),
    marginBottom: hp(3),
    shadowColor: colors.uberBlack,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  btnDisabled: {
    opacity: 0.6,
  },
  btnText: {
    color: colors.textInverse,
    fontSize: hp(2),
    fontWeight: '700',
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '90%',
    alignSelf: 'center',
    marginVertical: hp(3),
  },
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: colors.borderMedium,
  },
  dividerText: {
    marginHorizontal: wp(3),
    color: colors.textSecondary,
    fontSize: hp(1.7),
    fontWeight: '500',
  },
  socialLoginContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '90%',
    alignSelf: 'center',
    marginTop: hp(1),
    marginBottom: hp(4),
  },
  socialIcon: {
    width:Platform.OS=="ios"?"45%":"100%",
    height: hp(7),
    borderRadius: 12,
    backgroundColor: colors.backgroundSecondary,
    borderWidth: 1,
    borderColor: colors.borderLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: wp(1),
    shadowColor: colors.uberBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  registerLink: {
    alignSelf: 'center',
    marginTop: hp(0),
    marginBottom: hp(2),
  },
  registerText: {
    color: colors.textPrimary,
    fontSize: hp(1.8),
    textAlign: 'center',
  },
  registerNow: {
    color: colors.uberBlack,
    fontWeight: '700',
  },
  switchContainer: {
    flexDirection: 'row',
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 12,
    width: '100%',
    marginVertical: hp(2.5),
    position: 'relative',
    height: hp(6),
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  switchIndicator: {
    position: 'absolute',
    width: '50%',
    height: '100%',
    backgroundColor: colors.uberBlack,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.uberBlack,
  },
  switchButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
    borderRadius: 10,
  },
  switchButtonActive: {
    backgroundColor: 'transparent',
  },
  switchText: {
    color: colors.textSecondary,
    fontSize: hp(1.7),
    fontWeight: '600',
    textAlign: 'center',
  },
  switchTextActive: {
    color: colors.textInverse,
    fontWeight: '700',
  },
  guestBtn: {
    width: '90%',
    paddingVertical: hp(2),
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 12,
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: hp(1),
    marginBottom: hp(2),
    borderWidth: 1,
    borderColor: colors.borderLight,
    shadowColor: colors.uberBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  guestBtnText: {
    color: colors.textPrimary,
    fontSize: hp(2),
    fontWeight: '700',
  },
});

