import { I18nManager, StyleSheet } from 'react-native';
import { colors } from "../../utils/colors";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.backgroundPrimary,
  },
  mainContainer: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
  },
  stepContainer: {
    flex: 1,
    paddingHorizontal: wp(5),
  },
  formContainer: {
    flex: 1,
    paddingTop: hp(2.5),
    gap: hp(2.5),
  },
  inputContainer: {
    width: '100%',
  },
  label: {
    fontSize: hp(1.8),
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: hp(1),
  },
  input: {
    height: hp(7),
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: 12,
    paddingHorizontal: wp(4),
    marginBottom: hp(0.5),
    backgroundColor: colors.backgroundSecondary,
    color: colors.textPrimary,
    fontSize: hp(1.8),
    shadowColor: colors.uberBlack,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  passwordContainer: {
    height: hp(7),
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: 12,
    paddingHorizontal: wp(4),
    marginBottom: hp(0.5),
    backgroundColor: colors.backgroundSecondary,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: colors.uberBlack,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  passwordContainerError: {
    borderColor: colors.error,
  },
  passwordInput: {
    flex: 1,
    fontSize: hp(1.8),
    height: '100%',
    color: colors.textPrimary,
    textAlign:I18nManager.isRTL? "right":"left"
  },
  inputError: {
    borderColor: colors.error,
  },
  errorText: {
    color: colors.error,
    fontSize: hp(1.5),
    marginTop: hp(0.5),
    marginBottom: hp(1),
    marginLeft: wp(1),
  },
  buttonContainer: {
    paddingHorizontal: wp(5),
    paddingBottom: hp(3),
    backgroundColor: colors.backgroundPrimary,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    paddingTop: hp(2),
    justifyContent: 'center',
  },
  nextButton: {
    backgroundColor: colors.uberBlack,
    height: hp(7),
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.uberBlack,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  loginButtonDisabled: {
    opacity: 0.6,
  },
  nextButtonText: {
    color: colors.textInverse,
    fontSize: hp(2),
    fontWeight: '700',
  },
  menuContainer: {
    marginTop: hp(2.5),
    paddingHorizontal: wp(5),
  },
  menuButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: hp(2),
    paddingHorizontal: wp(5),
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 12,
    marginBottom: hp(1.5),
    borderWidth: 1,
    borderColor: colors.borderLight,
    shadowColor: colors.uberBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  menuButtonText: {
    fontSize: hp(2),
    fontWeight: '600',
    color: colors.textPrimary,

  },
  arrowIcon: {
    width: wp(5),
    height: wp(5),
    tintColor: colors.textSecondary,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.uberBlack,
    padding: hp(2),
    margin: wp(5),
    borderRadius: 12,
    shadowColor: colors.uberBlack,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  logoutIcon: {
    width: wp(5),
    height: wp(5),
    marginRight: wp(2.5),
    tintColor: colors.textInverse,
  },
  logoutText: {
    fontSize: hp(1.9),
    fontWeight: '700',
    color: colors.textInverse,
  },
  header: {
    backgroundColor: colors.uberBlack,
    height: hp(25),
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: hp(5),
  },
  settingsButton: {
    position: "absolute",
    top: hp(5),
    right: wp(5),
    padding: wp(2),
  },
  profileImage: {
    width: wp(25),
    height: wp(25),
    borderRadius: wp(12.5),
    borderWidth: 2,
    borderColor: colors.textInverse,
    objectFit: "cover",
  },
  userName: {
    color: colors.textInverse,
    fontSize: hp(2.5),
    fontWeight: "700",
    marginTop: hp(1.5),
  },
  userPhone: {
    color: colors.textInverse,
    fontSize: hp(2.1),
    fontWeight: "500",
    marginTop: hp(0.5),
  },
  userEmail: {
    color: colors.textInverse,
    fontSize: hp(2.1),
    fontWeight: "500",
    marginTop: hp(0.5),
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 16,
    padding: hp(2.5),
    borderWidth: 1,
    borderColor: colors.borderLight,
    marginHorizontal: wp(5),
    marginTop: -hp(8),
    shadowColor: colors.uberBlack,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  statItem: {
    alignItems: "center",
    flex: 1,
  },
  statIcon: {
    width: wp(10),
    height: wp(10),
    marginBottom: hp(1),
    tintColor: colors.uberBlue,
  },
  statValue: {
    color: colors.textPrimary,
    fontSize: hp(2.2),
    fontWeight: "700",
    marginTop: hp(0.5),
    textAlign: 'center',
  },
  statLabel: {
    color: colors.textSecondary,
    fontSize: hp(1.6),
    fontWeight: "500",
    marginTop: hp(0.5),
    textAlign: 'center',
  },
  // Tab Navigation Styles
  tabBar: {
    backgroundColor: colors.backgroundPrimary,
    elevation: 0,
    shadowOpacity: 0,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  tabLabel: {
    textTransform: 'none',
    fontSize: hp(1.8),
    fontWeight: '600',
  },
  tabIndicator: {
    backgroundColor: colors.uberBlack,
    height: 3,
  },
  // Section Styles
  sectionContainer: {
    flex: 1,
    backgroundColor: colors.backgroundPrimary,
    paddingHorizontal: wp(5),
    paddingVertical: hp(2.5),
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: hp(2.2),
    fontWeight: '700',
    marginBottom: hp(2.5),
  },
  inputContainer: {
    marginBottom: hp(2.5),
  },
  inputLabel: {
    color: colors.textPrimary,
    fontSize: hp(1.8),
    marginBottom: hp(1),
  },
  input: {
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: 12,
    padding: hp(1.8),
    color: colors.textPrimary,
    fontSize: hp(1.8),
    flex:1,
    backgroundColor: colors.backgroundSecondary,
    shadowColor: colors.uberBlack,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  inputError: {
    borderColor: colors.error,
  },
  saveButton: {
    backgroundColor: colors.uberBlack,
    padding: hp(2),
    borderRadius: 12,
    alignItems: 'center',
    marginTop: hp(2.5),
    shadowColor: colors.uberBlack,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  saveButtonText: {
    color: colors.textInverse,
    fontSize: hp(2),
    fontWeight: '700',
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.6)",
  },
  modalContent: {
    width: "90%",
    backgroundColor: colors.backgroundPrimary,
    borderRadius: 20,
    padding: hp(3),
    alignItems: "center",
    shadowColor: colors.uberBlack,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  modalIconContainer: {
    width: wp(20),
    height: wp(20),
    borderRadius: wp(10),
    backgroundColor: colors.uberBlueLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: hp(2),
  },
  modalTitle: {
    color: colors.textPrimary,
    fontWeight: "700",
    fontSize: hp(2.4),
    marginBottom: hp(1.5),
    textAlign: 'center',
  },
  modalMessage: {
    fontSize: hp(1.8),
    color: colors.textSecondary,
    textAlign: "center",
    marginBottom: hp(3),
    lineHeight: hp(2.5),
  },
  modalButtons: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: wp(3),
  },
  modalButton: {
    flex: 1,
    padding: hp(1.8),
    borderRadius: 12,
    alignItems: "center",
    justifyContent: 'center',
  },
  modalButtonPrimary: {
    backgroundColor: colors.uberBlack,
  },
  modalButtonSecondary: {
    backgroundColor: colors.backgroundSecondary,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  modalButtonText: {
    fontSize: hp(1.8),
    fontWeight: "700",
    color: colors.textInverse,
  },
  modalButtonTextSecondary: {
    color: colors.textPrimary,
  },
  // Error Styles
  errorText: {
    color: colors.error,
    fontSize: hp(1.5),
    marginTop: hp(0.5),
  },
  // Help Section Styles
  helpOptionsContainer: {
    marginTop: hp(2.5),
    marginBottom: hp(1.5),
  },
  helpOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.uberBlack,
    padding: hp(2),
    borderRadius: 12,
    marginBottom: hp(1.5),
    shadowColor: colors.uberBlack,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  helpOptionText: {
    color: colors.textInverse,
    fontSize: hp(1.9),
    marginLeft: wp(3),
    fontWeight: '700',
  },
  faqContainer: {
   // marginTop: 20,
  },
  faqTitle: {
    color: colors.textPrimary,
    fontSize: hp(2.2),
    fontWeight: '700',
    marginBottom: hp(2),
  },
  faqItem: {
    borderWidth:1,
    borderColor:colors.borderLight,
    backgroundColor: colors.backgroundSecondary,
    padding: hp(2),
    borderRadius: 12,
    marginBottom: hp(1.5),
    shadowColor: colors.uberBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  faqQuestion: {
    color: colors.textPrimary,
    fontSize: hp(1.8),
    fontWeight: '600',
    marginBottom: hp(1),
  },
  faqAnswer: {
    color: colors.textSecondary,
    fontSize: hp(1.6),
    lineHeight: hp(2.2),
  },
  passwordInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
    flex:1
  },
  eyeIcon: {
    marginStart: wp(3),
    height:"100%",
    width:wp(10),
    alignItems:"center",
    justifyContent:"center",
    color: colors.textSecondary,
  },
  languageButtons: {
    width: '100%',
    gap: hp(1.5),
    marginBottom: hp(2.5),
  },
  languageButton: {
    width: '100%',
    padding: hp(1.8),
    borderRadius: 12,
    alignItems: 'center',
    borderWidth:1,
    borderColor:colors.borderLight,
    flexDirection:'row',
    backgroundColor: colors.backgroundSecondary,
    shadowColor: colors.uberBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
});

