import {StyleSheet} from 'react-native';
import {heightPercentageToDP as hp} from 'react-native-responsive-screen';
import {colors} from '../../utils/colors';

export const styles = StyleSheet.create({
  container: {
    paddingHorizontal: 0,
    zIndex: 999999999,
    height: 50,
  },
  stepContainer: {
    flex: 1,
    backgroundColor: colors.backgroundPrimary,
  },
  header: {
    height: 60,
    backgroundColor: colors.uberBlack,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingHorizontal: 20,
    alignItems: 'center',
    flexDirection: 'row',
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  nextButton: {
    backgroundColor: colors.uberBlack,
    padding: 16,
    borderRadius: 12,
    width: '90%',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 20,
    shadowColor: colors.uberBlack,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  containerBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  option: {
    flexDirection: 'row',
    backgroundColor: colors.backgroundSecondary,
    width: '48%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  texte: {
    fontWeight: '600',
    color: colors.textPrimary,
    fontSize: hp(2.2),
  },
  text: {
    fontWeight: '400',
    color: colors.textSecondary,
    fontSize: hp(1.8),
  },
  yellowButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.uberBlue,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.uberBlue,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  buttonText: {
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: hp(2),
    fontWeight: '600',
    color: colors.textInverse,
  },
  countValue: {
    fontSize: hp(2.2),
    marginHorizontal: 12,
    color: colors.textPrimary,
    fontWeight: '500',
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    marginLeft: 16,
    color: colors.textInverse,
    marginTop: 8,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 8,
    paddingHorizontal: 16,
  },
  currentLocation: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    height: 64,
    width: '100%',
    paddingHorizontal: 16,
  },
  formContainer: {
    flex: 1,
    justifyContent: 'flex-start',
    backgroundColor: colors.backgroundPrimary,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  dateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '48%',
  },
  autocompleteContainer: {
    flex: 1,
  },
  textInput: {
    height: 48,
    borderColor: colors.borderLight,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    backgroundColor: colors.backgroundPrimary,
  },
  logo: {
    marginLeft: 12,
  },
  dateInput: {
    flex: 1,
    height: 48,
    borderColor: colors.borderLight,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 16,
    justifyContent: 'center',
    backgroundColor: colors.backgroundPrimary,
  },
  dateText: {
    fontSize: 16,
    color: colors.textPrimary,
  },
  timeInputsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  timeInput: {
    width: 64,
    height: 48,
    borderColor: colors.borderLight,
    borderWidth: 1,
    borderRadius: 12,
    textAlign: 'center',
    fontSize: 16,
    backgroundColor: colors.backgroundPrimary,
  },
  timeSeparator: {
    marginHorizontal: 8,
    fontSize: 20,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  switchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginBottom: 24,
    paddingHorizontal: 16,
  },
  switchText: {
    color: colors.textInverse,
    fontSize: hp(1.6),
    fontWeight: '500',
  },
  iconContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    alignSelf: 'flex-end',
    paddingHorizontal: 16,
  },
  markerContainer: {
    width: 100,
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  waveCircle: {
    position: 'absolute',
    width: 50,
    height: 50,
    borderRadius: 25,
  },
  confirmButton: {
    width: "100%",
    flex: 1,
    backgroundColor: colors.uberBlack,
    borderRadius: 12,
    paddingVertical: 18,
    alignItems: 'center',
    shadowColor: colors.uberBlack,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
    marginHorizontal: 16,
  },
  confirmButtonText: {
    color: colors.textInverse,
    fontSize: 18,
    fontWeight: '700',
  },
  mapContainer: {
    ...StyleSheet.absoluteFillObject
  },
  contentContainer: {
    position: 'absolute',
    top: '0.5%',
    left: 0,
    right: 0,
    backgroundColor: colors.backgroundPrimary,
    padding: 8,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    borderBottomLeftRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  headerContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    padding: 8,
  },
  step1Wrapper: {
    backgroundColor: colors.backgroundPrimary,
    borderRadius: 20,
    padding: 20,
    margin: 16,
    paddingTop: 16,
    alignItems: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 6,
    width: '92%',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  stepperContainer: {
    alignItems: 'center',
    marginRight: 12,
    width: 32,
  },
  stepperCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.uberBlack,
    borderWidth: 2,
    borderColor: colors.uberBlack,
    marginBottom: 4,
    marginTop: 48,
  },
  stepperLine: {
    width: 2,
    height: 76,
    backgroundColor: colors.borderMedium,
    marginVertical: 4,
  },
  stepperIconContainer: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  stepContent: {
    flex: 1,
    paddingLeft: 8,
  },
  step1Label: {
    fontSize: 18,
    color: colors.textPrimary,
    fontWeight: '600',
    marginBottom: 8,
  },
  pickOffContainer: {
    marginTop: 20,
    marginBottom: 12,
  },
  pickOffLabel: {
    color: colors.textSecondary,
    fontSize: 14,
    marginBottom: 4,
    fontWeight: '500',
  },
  destinationLabel: {
    fontWeight: '700',
    fontSize: 18,
    color: colors.textInverse,
    marginTop: 4,
    marginBottom: 16,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  carIcon: {
    marginLeft: 12,
  },
  countdownOverlay: {
    position: 'absolute',
    top: 0, 
    left: 0, 
    right: 0, 
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.75)',
    zIndex: 999999,
    justifyContent: 'center',
    alignItems: 'center',
  },
  countdownTitle: {
    color: colors.textInverse,
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 40,
    position: "absolute",
    top: "20%"
  },
  countdownRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 24,
    position: "absolute",
    top: "30%"
  },
  countdownBlock: {
    alignItems: 'center',
    marginHorizontal: 12,
  },
  countdownNumber: {
    color: colors.textInverse,
    fontSize: 44,
    fontWeight: '700',
  },
  countdownLabel: {
    color: colors.textInverse,
    fontSize: 16,
    marginTop: 8,
    fontWeight: '500',
  },
  countdownColon: {
    color: colors.textInverse,
    fontSize: 44,
    fontWeight: '700',
    marginHorizontal: 4,
    marginTop: -8,
  },
});

